###############################################################################
# For local use only
###############################################################################
services:
  web:
    image: "esoraider-server:dev"
    build:
      context: .
    env_file: ./esoraider_server/.env
    command: bash ./entrypoint.sh
    ports:
      - 8000:8000
    init: true
