[tool.poetry]
name = "esoraider-server"
version = "0.1.0"
description = ""
authors = ["Dreemurro <dr33murro@gmail.com>"]
readme = "README.MD"
packages = [{ include = "esoraider_server" }]
package-mode = false

[tool.poetry.dependencies]
python = "3.9.*"
blacksheep = "1.2.20"
dataclasses-json = "0.5.7"
gql = { extras = ["aiohttp"], version = "3.5.0" }
gunicorn = "22.0.0"
loguru = "0.6.0"
portion = "2.3.1"
python-dotenv = "0.21.1"
requests-oauthlib = "1.3.1"
uvicorn = "0.30.1"

[tool.poetry.group.dev.dependencies]
autopep8 = "*"
isort = "*"
mypy = "*"
nitpick = "*"
wemake-python-styleguide = "*"

[tool.poetry.group.tests.dependencies]
pytest = "*"
pytest-asyncio = "*"

[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style.toml"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
