---

# This compose-file is production only. So, it should not be called directly.
#
# Instead, it should be a part of your deployment strategy.
# This setup is supposed to be used with `docker-swarm`.

version: "3.8"
services:
  caddy:
    image: "caddy:2.6.4"
    restart: unless-stopped
    volumes:
      - caddy-config:/config # configuration autosaves
      - caddy-data:/data # saving certificates
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
      - source: caddy_test
        target: /etc/ci.sh
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxynet

  web:
    <<:
      # Image for production:
      &web
      image: "ghcr.io/dreemurro/esoraider-server:latest"
      build:
        target: production_build
        args:
          CURRENT_ENV: production

      restart: unless-stopped

    command: bash ./docker/blacksheep/gunicorn.sh
    networks:
      - proxynet
    expose:
      - 8000

networks:
  # Network for your proxy server and application to connect them,
  # do not use it for anything else!
  proxynet:


configs:
  caddy_config:
    file: ./docker/caddy/Caddyfile
  caddy_test:
    file: ./docker/caddy/ci.sh

volumes:
  caddy-config:
  caddy-data:
