name: build-container

on: [workflow_dispatch, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          envkey_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          envkey_DEBUG: ${{ secrets.DEBUG }}
          envkey_SHOW_ERROR_DETAILS: ${{ secrets.SHOW_ERROR_DETAILS }}
          envkey_DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          envkey_TLS_EMAIL: ${{ secrets.TLS_EMAIL }}
          directory: esoraider_server
          fail_on_empty: true
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/blacksheep/Dockerfile
          push: true
          tags: |
            ghcr.io/dreemurro/esoraider-server:latest
