name: deploy-swarm

on: [workflow_dispatch, pull_request]

jobs:
  deploy-swarm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          envkey_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          envkey_DEBUG: ${{ secrets.DEBUG }}
          envkey_SHOW_ERROR_DETAILS: ${{ secrets.SHOW_ERROR_DETAILS }}
          envkey_DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          envkey_TLS_EMAIL: ${{ secrets.TLS_EMAIL }}
          directory: esoraider_server
          fail_on_empty: true
      - name: Deploy to Docker swarm
        uses: sulthonzh/docker-remote-deployment-action@v0.1.2-beta
        with:
          remote_docker_host: ${{ secrets.USERNAME }}@${{ secrets.HOST }}
          remote_docker_port: ${{ secrets.PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          docker_registry_username: ${{ github.repository_owner }}
          docker_registry_password: ${{ secrets.GITHUB_TOKEN }}
          docker_registry_uri: ghcr.io
          args: -c docker/docker-compose.prod.yml esoraider-server
